"""Hardware-free tests for D500 protocol and drone-frame coordinates."""

from __future__ import annotations

import math
from pathlib import Path
import struct
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from components.radar_driver import (  # noqa: E402
    D500PacketParser,
    D500RadarComponent,
    DroneGlobalAlignment,
    ICPResult,
    ICPScanMatcher,
    Pose2D,
    RadarMount,
    RadarOdometry,
    RadarOdometryUpdate,
    RadarPacket,
    RadarPoint,
    RadarScan,
    RadarScanAssembler,
    RectangleFieldCalibrator,
    RectangularWallReference,
    WallFusionConfig,
    WallLineConfig,
    WallLineLocalizer,
    WallPoseObservation,
    calculate_d500_crc8,
    fuse_wall_observation,
    rotate_cw,
    scan_points_in_drone_global,
)


def build_frame(*, start_centideg: int = 1000, stop_centideg: int = 2100) -> bytes:
    values: list[int] = [3600, start_centideg]
    for index in range(12):
        values.extend((1000 + index, 80 + index))
    values.extend((stop_centideg, 1234))
    payload = struct.pack("<HH" + "HB" * 12 + "HH", *values)
    frame_without_crc = b"\x54\x2c" + payload
    return frame_without_crc + bytes((calculate_d500_crc8(frame_without_crc),))


class D500ProtocolTests(unittest.TestCase):
    def test_crc_matches_drone_reference_table_vector(self) -> None:
        # Expected value generated by FlightController/Components/Utils.py.
        self.assertEqual(build_frame()[-1], 0xE7)

    def test_incremental_decode_and_angles(self) -> None:
        frame = build_frame()
        parser = D500PacketParser()
        self.assertEqual(parser.feed(b"noise" + frame[:10]), [])
        packets = parser.feed(frame[10:])
        self.assertEqual(len(packets), 1)
        packet = packets[0]
        self.assertEqual(packet.rotation_speed_deg_s, 3600)
        self.assertEqual(packet.timestamp_ms, 1234)
        self.assertEqual(packet.points[0].angle_cw_deg, 10.0)
        self.assertEqual(packet.points[-1].angle_cw_deg, 21.0)
        self.assertEqual(packet.points[5].distance_mm, 1005)
        self.assertEqual(parser.stats.decoded_frames, 1)
        self.assertEqual(parser.stats.discarded_bytes, 5)

    def test_bad_crc_resynchronizes_to_following_frame(self) -> None:
        bad = bytearray(build_frame())
        bad[10] ^= 0x40
        good = build_frame(start_centideg=2200, stop_centideg=3300)
        parser = D500PacketParser()
        packets = parser.feed(bytes(bad) + good)
        self.assertEqual(len(packets), 1)
        self.assertEqual(packets[0].start_angle_cw_deg, 22.0)
        self.assertEqual(parser.stats.crc_errors, 1)

    def test_scan_assembler_emits_at_angle_wrap(self) -> None:
        first_points = tuple(RadarPoint(300 + index * 5, 1000, 100) for index in range(12))
        middle_points = tuple(RadarPoint(index * 5, 1000, 100) for index in range(12))
        final_points = tuple(RadarPoint(300 + index * 5, 1000, 100) for index in range(12))
        next_points = tuple(RadarPoint(index * 5, 1000, 100) for index in range(12))
        assembler = RadarScanAssembler(min_points=10)
        first = RadarPacket(3600, 300, 355, 10, first_points)
        second = RadarPacket(3600, 0, 55, 20, middle_points)
        final = RadarPacket(3600, 300, 355, 30, final_points)
        following = RadarPacket(3600, 0, 55, 40, next_points)
        self.assertEqual(assembler.feed(first), [])
        self.assertEqual(assembler.feed(second), [])  # First wrap discards startup partial scan.
        self.assertEqual(assembler.feed(final), [])
        scans = assembler.feed(following)
        self.assertEqual(len(scans), 1)
        self.assertEqual(len(scans[0].points), 24)


class DroneCoordinateTests(unittest.TestCase):
    def assertPointAlmostEqual(self, actual, expected, places=6) -> None:
        self.assertAlmostEqual(actual[0], expected[0], places=places)
        self.assertAlmostEqual(actual[1], expected[1], places=places)

    def test_raw_angle_uses_forward_x_left_y_and_clockwise_positive(self) -> None:
        point = RadarPoint(90.0, 1000, 100)
        self.assertPointAlmostEqual(point.sensor_xy_cm(), (0.0, -100.0))

    def test_radar_mount_rotation_and_offset(self) -> None:
        mount = RadarMount(x_forward_cm=10, y_left_cm=3, yaw_cw_deg=90)
        self.assertPointAlmostEqual(mount.sensor_to_body((100, 0)), (10, -97))

    def test_reference_pose_maps_exactly_into_drone_global(self) -> None:
        car_reference = Pose2D(100, 20, 90)
        drone_reference = Pose2D(1000, 2000, -90)
        alignment = DroneGlobalAlignment.from_reference(car_reference, drone_reference)
        transformed = alignment.pose_to_global(car_reference)
        self.assertAlmostEqual(transformed.x_cm, drone_reference.x_cm)
        self.assertAlmostEqual(transformed.y_cm, drone_reference.y_cm)
        self.assertAlmostEqual(transformed.yaw_cw_deg, drone_reference.yaw_cw_deg)
        self.assertAlmostEqual(abs(alignment.yaw_offset_cw_deg), 180.0)

    def test_global_alignment_inverse_round_trip(self) -> None:
        alignment = DroneGlobalAlignment(120, -45, 73)
        local = Pose2D(32, -18, -125)
        recovered = alignment.pose_to_local(alignment.pose_to_global(local))
        self.assertAlmostEqual(recovered.x_cm, local.x_cm)
        self.assertAlmostEqual(recovered.y_cm, local.y_cm)
        self.assertAlmostEqual(recovered.yaw_cw_deg, local.yaw_cw_deg)

    def test_scan_points_are_written_in_drone_global_frame(self) -> None:
        scan = RadarScan((RadarPoint(0, 1000, 100),), 0, 3600)
        car_pose = Pose2D(10, 20, 90)
        mount = RadarMount()
        alignment = DroneGlobalAlignment(1000, 2000, 90)
        points = scan_points_in_drone_global(scan, car_pose, mount, alignment)
        # Sensor +X -> car-local -Y at car yaw 90; then -> drone-global -X.
        self.assertPointAlmostEqual(points[0], (920, 1990))


class ICPTests(unittest.TestCase):
    def test_recovers_clockwise_current_to_reference_transform(self) -> None:
        current = [
            (35 * math.cos(i * 0.37) + i * 1.1, 28 * math.sin(i * 0.53) - i * 0.4)
            for i in range(80)
        ]
        reference = []
        for point in current:
            x_cm, y_cm = rotate_cw(*point, 3.0)
            reference.append((x_cm + 4.0, y_cm - 2.0))
        matcher = ICPScanMatcher(max_correspondence_cm=20, min_correspondences=30)
        result = matcher.match(reference, current)
        pose = result.transform_current_to_reference
        self.assertAlmostEqual(pose.x_cm, 4.0, delta=0.15)
        self.assertAlmostEqual(pose.y_cm, -2.0, delta=0.15)
        self.assertAlmostEqual(pose.yaw_cw_deg, 3.0, delta=0.15)
        self.assertLess(result.mean_error_cm, 0.15)

    def test_stationary_subthreshold_icp_is_fresh_valid_localization(self) -> None:
        class SubthresholdMatcher:
            def __init__(self) -> None:
                self.references = []

            def match(self, reference, current):
                self.references.append(tuple(reference))
                return ICPResult(Pose2D(0.4, -0.3, 0.2), 80, 0.5, 2)

        matcher = SubthresholdMatcher()
        odometry = RadarOdometry(matcher=matcher)
        first = RadarScan(
            tuple(RadarPoint(float(angle), 1000, 200) for angle in range(0, 360, 10)),
            1,
            3600,
        )
        second = RadarScan(
            tuple(RadarPoint(float(angle), 1001, 200) for angle in range(0, 360, 10)),
            2,
            3600,
        )
        third = RadarScan(
            tuple(RadarPoint(float(angle), 1002, 200) for angle in range(0, 360, 10)),
            3,
            3600,
        )

        odometry.update(first)
        update = odometry.update(second)
        odometry.update(third)

        self.assertTrue(update.accepted)
        self.assertIsNone(update.rejection_reason)
        self.assertEqual(update.pose, Pose2D())
        self.assertEqual(
            matcher.references[-1],
            tuple(point.sensor_xy_cm() for point in first.points),
        )

    def test_subthreshold_motion_accumulates_against_keyframe(self) -> None:
        class AccumulatingMatcher:
            def __init__(self) -> None:
                self.references = []
                self.deltas = iter((0.8, 1.6, 2.4, 0.7))

            def match(self, reference, current):
                self.references.append(tuple(reference))
                return ICPResult(Pose2D(next(self.deltas), 0.0, 0.0), 80, 0.5, 2)

        matcher = AccumulatingMatcher()
        odometry = RadarOdometry(matcher=matcher)
        scans = [
            RadarScan(
                tuple(
                    RadarPoint(float(angle), 1000 + index, 200)
                    for angle in range(0, 360, 10)
                ),
                index,
                3600,
            )
            for index in range(5)
        ]

        updates = [odometry.update(scan) for scan in scans]

        self.assertEqual(updates[1].pose, Pose2D())
        self.assertEqual(updates[2].pose, Pose2D())
        self.assertAlmostEqual(updates[3].pose.x_cm, 2.4)
        self.assertAlmostEqual(updates[4].pose.x_cm, 2.4)
        first_keyframe = tuple(point.sensor_xy_cm() for point in scans[0].points)
        third_keyframe = tuple(point.sensor_xy_cm() for point in scans[3].points)
        self.assertEqual(matcher.references[0], first_keyframe)
        self.assertEqual(matcher.references[1], first_keyframe)
        self.assertEqual(matcher.references[2], first_keyframe)
        self.assertEqual(matcher.references[3], third_keyframe)

    def test_subthreshold_yaw_accumulates_against_keyframe(self) -> None:
        class AccumulatingYawMatcher:
            def __init__(self) -> None:
                self.references = []
                self.deltas = iter((0.3, 0.7, 1.2))

            def match(self, reference, current):
                self.references.append(tuple(reference))
                return ICPResult(Pose2D(0.0, 0.0, next(self.deltas)), 80, 0.5, 2)

        matcher = AccumulatingYawMatcher()
        odometry = RadarOdometry(matcher=matcher)
        scans = [
            RadarScan(
                tuple(
                    RadarPoint(float(angle), 1000 + index, 200)
                    for angle in range(0, 360, 10)
                ),
                index,
                3600,
            )
            for index in range(4)
        ]

        updates = [odometry.update(scan) for scan in scans]

        self.assertEqual(updates[1].pose, Pose2D())
        self.assertEqual(updates[2].pose, Pose2D())
        self.assertAlmostEqual(updates[3].pose.yaw_cw_deg, 1.2)
        first_keyframe = tuple(point.sensor_xy_cm() for point in scans[0].points)
        self.assertEqual(matcher.references[0], first_keyframe)
        self.assertEqual(matcher.references[1], first_keyframe)
        self.assertEqual(matcher.references[2], first_keyframe)

    def test_bad_subthreshold_icp_is_rejected_before_stationary_handling(self) -> None:
        class BadMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(0.2, 0.1, 0.1), 80, 20.0, 2)

        odometry = RadarOdometry(matcher=BadMatcher(), max_mean_error_cm=12.0)
        scan = RadarScan(
            tuple(RadarPoint(float(angle), 1000, 200) for angle in range(0, 360, 10)),
            1,
            3600,
        )
        odometry.update(scan)

        update = odometry.update(scan)

        self.assertFalse(update.accepted)
        self.assertEqual(update.rejection_reason, "error gate")

    def test_impossible_ackermann_lateral_jump_is_rejected(self) -> None:
        class SidewaysMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(0.0, 8.0, 0.0), 80, 0.5, 2)

        odometry = RadarOdometry(matcher=SidewaysMatcher())
        scan = RadarScan(
            tuple(RadarPoint(float(angle), 1000, 200) for angle in range(0, 360, 10)),
            1,
            3600,
        )
        odometry.update(scan)

        update = odometry.update(scan)

        self.assertFalse(update.accepted)
        self.assertEqual(update.rejection_reason, "Ackermann lateral gate")
        self.assertEqual(update.pose, Pose2D())

    def test_ackermann_arc_motion_is_accepted(self) -> None:
        yaw_cw_deg = 10.0
        x_cm = 10.0
        y_cm = -x_cm * math.tan(math.radians(yaw_cw_deg) / 2.0)

        class ArcMatcher:
            def match(self, reference, current):
                return ICPResult(Pose2D(x_cm, y_cm, yaw_cw_deg), 80, 0.5, 2)

        odometry = RadarOdometry(matcher=ArcMatcher())
        scan = RadarScan(
            tuple(RadarPoint(float(angle), 1000, 200) for angle in range(0, 360, 10)),
            1,
            3600,
        )
        odometry.update(scan)

        update = odometry.update(scan)

        self.assertTrue(update.accepted)
        self.assertAlmostEqual(update.pose.x_cm, x_cm)
        self.assertAlmostEqual(update.pose.y_cm, y_cm)
        self.assertAlmostEqual(update.pose.yaw_cw_deg, yaw_cw_deg)


def rectangular_wall_scan(pose_in_wall: Pose2D, *, include_right: bool = True) -> RadarScan:
    wall_points: list[tuple[float, float]] = []
    wall_points.extend((0.0, float(y_cm)) for y_cm in range(0, 205, 5))
    if include_right:
        wall_points.extend((float(x_cm), 0.0) for x_cm in range(0, 245, 5))
    radar_points = []
    for wall_x, wall_y in wall_points:
        relative_x = wall_x - pose_in_wall.x_cm
        relative_y = wall_y - pose_in_wall.y_cm
        body_x, body_y = rotate_cw(
            relative_x,
            relative_y,
            -pose_in_wall.yaw_cw_deg,
        )
        distance_cm = math.hypot(body_x, body_y)
        angle_cw = math.degrees(math.atan2(-body_y, body_x)) % 360.0
        radar_points.append(RadarPoint(angle_cw, round(distance_cm * 10), 200))
    return RadarScan(tuple(radar_points), 0, 3600)


class WallLineFusionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.wall_to_global = DroneGlobalAlignment(500, 200, 90)
        self.reference = RectangularWallReference(self.wall_to_global)
        self.localizer = WallLineLocalizer(
            self.reference,
            config=WallLineConfig(min_points_per_wall=10, min_line_span_cm=40),
        )

    def test_wall_lines_recover_absolute_pose_from_drifted_prediction(self) -> None:
        true_wall_pose = Pose2D(100, 80, 15)
        predicted_wall_pose = Pose2D(108, 73, 20)
        observation = self.localizer.observe(
            rectangular_wall_scan(true_wall_pose),
            self.wall_to_global.pose_to_global(predicted_wall_pose),
        )
        self.assertAlmostEqual(observation.x_cm, true_wall_pose.x_cm, delta=1.0)
        self.assertAlmostEqual(observation.y_cm, true_wall_pose.y_cm, delta=1.0)
        self.assertAlmostEqual(observation.yaw_cw_deg, true_wall_pose.yaw_cw_deg, delta=1.0)
        self.assertGreaterEqual(observation.back_wall_points, 10)
        self.assertGreaterEqual(observation.right_wall_points, 10)

    def test_partial_back_wall_corrects_x_but_not_y(self) -> None:
        true_wall_pose = Pose2D(100, 80, 15)
        predicted_wall_pose = Pose2D(108, 73, 20)
        observation = self.localizer.observe(
            rectangular_wall_scan(true_wall_pose, include_right=False),
            self.wall_to_global.pose_to_global(predicted_wall_pose),
        )
        self.assertIsNotNone(observation.x_cm)
        self.assertIsNone(observation.y_cm)
        self.assertIsNotNone(observation.yaw_cw_deg)

    def test_back_and_right_walls_localize_after_car_turns_around(self) -> None:
        true_pose = Pose2D(150, 120, 168)
        predicted_pose = Pose2D(143, 128, 162)
        observation = self.localizer.observe(
            rectangular_wall_scan(true_pose),
            self.wall_to_global.pose_to_global(predicted_pose),
        )
        self.assertAlmostEqual(observation.x_cm, true_pose.x_cm, delta=1.0)
        self.assertAlmostEqual(observation.y_cm, true_pose.y_cm, delta=1.2)
        self.assertAlmostEqual(observation.yaw_cw_deg, true_pose.yaw_cw_deg, delta=2.0)

    def test_fusion_applies_limited_correction(self) -> None:
        predicted_wall = Pose2D(110, 70, 20)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        observation = WallPoseObservation(100, 80, 10, 20, 20, 1, 1)
        result = fuse_wall_observation(
            predicted_global,
            observation,
            self.reference,
            WallFusionConfig(
                position_gain=0.25,
                yaw_gain=0.5,
                max_position_correction_cm=10.0,
                max_yaw_correction_deg=10.0,
            ),
        )
        self.assertTrue(result.accepted)
        fused_wall = self.wall_to_global.pose_to_local(result.fused_global_pose)
        self.assertAlmostEqual(fused_wall.x_cm, 107.5)
        self.assertAlmostEqual(fused_wall.y_cm, 72.5)
        self.assertAlmostEqual(fused_wall.yaw_cw_deg, 15)

    def test_large_false_wall_residual_is_rejected(self) -> None:
        predicted_wall = Pose2D(100, 80, 10)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        observation = WallPoseObservation(300, 80, 10, 20, 20, 1, 1)
        result = fuse_wall_observation(predicted_global, observation, self.reference)
        self.assertFalse(result.accepted)
        self.assertEqual(result.fused_global_pose, predicted_global)
        self.assertIn("residual gate", result.reason)

    def test_default_fusion_rejects_single_large_correction(self) -> None:
        predicted_wall = Pose2D(100, 80, 10)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        observation = WallPoseObservation(120, 50, 6, 20, 20, 1, 1)

        result = fuse_wall_observation(predicted_global, observation, self.reference)

        self.assertFalse(result.accepted)
        self.assertEqual(result.fused_global_pose, predicted_global)
        self.assertEqual(result.reason, "wall position correction gate")

    def test_default_fusion_rejects_single_large_yaw_correction(self) -> None:
        predicted_wall = Pose2D(100, 80, 10)
        predicted_global = self.wall_to_global.pose_to_global(predicted_wall)
        observation = WallPoseObservation(100, 80, 0, 20, 20, 1, 1)

        result = fuse_wall_observation(predicted_global, observation, self.reference)

        self.assertFalse(result.accepted)
        self.assertEqual(result.fused_global_pose, predicted_global)
        self.assertEqual(result.reason, "wall yaw correction gate")

    def test_component_writes_wall_correction_back_into_odometry(self) -> None:
        true_wall_pose = Pose2D(100, 80, 15)
        predicted_wall_pose = Pose2D(108, 73, 20)
        scan = rectangular_wall_scan(true_wall_pose)

        class OneScanAssembler:
            def feed(self, packet):
                return [scan]

        class FixedOdometry:
            def __init__(self):
                self.pose = predicted_wall_pose

            def update(self, incoming_scan):
                return RadarOdometryUpdate(self.pose, True, True)

        odometry = FixedOdometry()
        component = D500RadarComponent(
            alignment=self.wall_to_global,
            assembler=OneScanAssembler(),
            odometry=odometry,
            wall_localizer=self.localizer,
            wall_fusion_config=WallFusionConfig(
                update_every_scans=1,
                position_gain=1.0,
                yaw_gain=1.0,
                max_position_correction_cm=20.0,
                max_yaw_correction_deg=10.0,
            ),
        )
        dummy_packet = RadarPacket(3600, 0, 1, 0, ())
        update = component.process_packet(dummy_packet)[0]
        self.assertIsNotNone(update.wall_fusion)
        self.assertTrue(update.wall_fusion.accepted)
        corrected_wall = self.wall_to_global.pose_to_local(update.global_pose)
        self.assertAlmostEqual(corrected_wall.x_cm, true_wall_pose.x_cm, delta=1.0)
        self.assertAlmostEqual(corrected_wall.y_cm, true_wall_pose.y_cm, delta=1.0)
        self.assertAlmostEqual(corrected_wall.yaw_cw_deg, true_wall_pose.yaw_cw_deg, delta=1.0)
        self.assertEqual(odometry.pose, update.odometry.pose)
        self.assertGreater(len(update.global_points_cm), 0)


class RectangleStartupCalibrationTests(unittest.TestCase):
    def test_initial_position_is_origin_and_nearest_edge_becomes_x_axis(self) -> None:
        edge_ccw_from_car = 20.0
        wall_points = []
        for y_cm in range(-90, 131, 5):
            wall_points.extend(((-120, y_cm), (180, y_cm)))
        for x_cm in range(-120, 181, 5):
            wall_points.extend(((x_cm, -90), (x_cm, 130)))
        radar_points = []
        for global_x, global_y in wall_points:
            body_x, body_y = rotate_cw(
                global_x,
                global_y,
                -edge_ccw_from_car,
            )
            distance_cm = math.hypot(body_x, body_y)
            angle_cw = math.degrees(math.atan2(-body_y, body_x)) % 360
            radar_points.append(RadarPoint(angle_cw, round(distance_cm * 10), 200))
        scan = RadarScan(tuple(radar_points), 0, 3600)

        calibration = RectangleFieldCalibrator().calibrate([scan])
        self.assertAlmostEqual(calibration.initial_global_pose.x_cm, 0, delta=0.1)
        self.assertAlmostEqual(calibration.initial_global_pose.y_cm, 0, delta=0.1)
        self.assertAlmostEqual(
            calibration.selected_edge_ccw_from_car_deg,
            edge_ccw_from_car,
            delta=0.2,
        )
        self.assertAlmostEqual(calibration.min_x_cm, -120, delta=0.5)
        self.assertAlmostEqual(calibration.max_x_cm, 180, delta=0.5)
        self.assertAlmostEqual(calibration.min_y_cm, -90, delta=0.5)
        self.assertAlmostEqual(calibration.max_y_cm, 130, delta=0.5)


if __name__ == "__main__":
    unittest.main()
